# Generated by Django 5.2.5 on 2025-08-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_medicationorder_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
