# Generated by Django 5.2.5 on 2025-08-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('inventory', '0002_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_supply', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='medication',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication', to='hospitals.hospital'),
        ),
    ]
