# Generated by Django 5.2.5 on 2025-08-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('reports', '0002_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
        ),
    ]
